# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.workflower_api import WorkflowerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkflowerApi(unittest.TestCase):
    """WorkflowerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.workflower_api.WorkflowerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_parameters_create(self):
        """Test case for parameters_create

        """
        pass

    def test_parameters_delete(self):
        """Test case for parameters_delete

        """
        pass

    def test_parameters_list(self):
        """Test case for parameters_list

        """
        pass

    def test_parameters_partial_update(self):
        """Test case for parameters_partial_update

        """
        pass

    def test_parameters_read(self):
        """Test case for parameters_read

        """
        pass

    def test_parameters_update(self):
        """Test case for parameters_update

        """
        pass

    def test_targets_create(self):
        """Test case for targets_create

        """
        pass

    def test_targets_delete(self):
        """Test case for targets_delete

        """
        pass

    def test_targets_list(self):
        """Test case for targets_list

        """
        pass

    def test_targets_partial_update(self):
        """Test case for targets_partial_update

        """
        pass

    def test_targets_read(self):
        """Test case for targets_read

        """
        pass

    def test_targets_update(self):
        """Test case for targets_update

        """
        pass

    def test_tasks_create(self):
        """Test case for tasks_create

        """
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass

    def test_tasks_partial_update(self):
        """Test case for tasks_partial_update

        """
        pass

    def test_tasks_read(self):
        """Test case for tasks_read

        """
        pass

    def test_tasks_update(self):
        """Test case for tasks_update

        """
        pass

    def test_workflows_create(self):
        """Test case for workflows_create

        """
        pass

    def test_workflows_delete(self):
        """Test case for workflows_delete

        """
        pass

    def test_workflows_generate(self):
        """Test case for workflows_generate

        """
        pass

    def test_workflows_list(self):
        """Test case for workflows_list

        """
        pass

    def test_workflows_partial_update(self):
        """Test case for workflows_partial_update

        """
        pass

    def test_workflows_read(self):
        """Test case for workflows_read

        """
        pass

    def test_workflows_update(self):
        """Test case for workflows_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
