# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data4 import Data4  # noqa: E501
from swagger_client.rest import ApiException


class TestData4(unittest.TestCase):
    """Data4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData4(self):
        """Test Data4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data4.Data4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
