# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data11 import Data11  # noqa: E501
from swagger_client.rest import ApiException


class TestData11(unittest.TestCase):
    """Data11 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData11(self):
        """Test Data11"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data11.Data11()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
