# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.targets_api import TargetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTargetsApi(unittest.TestCase):
    """TargetsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.targets_api.TargetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_targets_create(self):
        """Test case for targets_create

        """
        pass

    def test_targets_delete(self):
        """Test case for targets_delete

        """
        pass

    def test_targets_list(self):
        """Test case for targets_list

        """
        pass

    def test_targets_partial_update(self):
        """Test case for targets_partial_update

        """
        pass

    def test_targets_read(self):
        """Test case for targets_read

        """
        pass

    def test_targets_update(self):
        """Test case for targets_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
