# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.creator_api import CreatorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreatorApi(unittest.TestCase):
    """CreatorApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.creator_api.CreatorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_results_create(self):
        """Test case for results_create

        """
        pass

    def test_results_delete(self):
        """Test case for results_delete

        """
        pass

    def test_results_list(self):
        """Test case for results_list

        """
        pass

    def test_results_partial_update(self):
        """Test case for results_partial_update

        """
        pass

    def test_results_read(self):
        """Test case for results_read

        """
        pass

    def test_results_update(self):
        """Test case for results_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
