# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.workflows_api import WorkflowsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.workflows_api.WorkflowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_workflows_create(self):
        """Test case for workflows_create

        """
        pass

    def test_workflows_delete(self):
        """Test case for workflows_delete

        """
        pass

    def test_workflows_generate(self):
        """Test case for workflows_generate

        """
        pass

    def test_workflows_list(self):
        """Test case for workflows_list

        """
        pass

    def test_workflows_partial_update(self):
        """Test case for workflows_partial_update

        """
        pass

    def test_workflows_read(self):
        """Test case for workflows_read

        """
        pass

    def test_workflows_update(self):
        """Test case for workflows_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
