# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parameters_api import ParametersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParametersApi(unittest.TestCase):
    """ParametersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parameters_api.ParametersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_parameters_create(self):
        """Test case for parameters_create

        """
        pass

    def test_parameters_delete(self):
        """Test case for parameters_delete

        """
        pass

    def test_parameters_list(self):
        """Test case for parameters_list

        """
        pass

    def test_parameters_partial_update(self):
        """Test case for parameters_partial_update

        """
        pass

    def test_parameters_read(self):
        """Test case for parameters_read

        """
        pass

    def test_parameters_update(self):
        """Test case for parameters_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
