# coding: utf-8

"""
    Workflower API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Data2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workflow': 'str',
        'salted_hash': 'str',
        'successful': 'bool'
    }

    attribute_map = {
        'workflow': 'workflow',
        'salted_hash': 'salted_hash',
        'successful': 'successful'
    }

    def __init__(self, workflow=None, salted_hash=None, successful=None):  # noqa: E501
        """Data2 - a model defined in Swagger"""  # noqa: E501

        self._workflow = None
        self._salted_hash = None
        self._successful = None
        self.discriminator = None

        if workflow is not None:
            self.workflow = workflow
        if salted_hash is not None:
            self.salted_hash = salted_hash
        if successful is not None:
            self.successful = successful

    @property
    def workflow(self):
        """Gets the workflow of this Data2.  # noqa: E501

          # noqa: E501

        :return: The workflow of this Data2.  # noqa: E501
        :rtype: str
        """
        return self._workflow

    @workflow.setter
    def workflow(self, workflow):
        """Sets the workflow of this Data2.

          # noqa: E501

        :param workflow: The workflow of this Data2.  # noqa: E501
        :type: str
        """

        self._workflow = workflow

    @property
    def salted_hash(self):
        """Gets the salted_hash of this Data2.  # noqa: E501

          # noqa: E501

        :return: The salted_hash of this Data2.  # noqa: E501
        :rtype: str
        """
        return self._salted_hash

    @salted_hash.setter
    def salted_hash(self, salted_hash):
        """Sets the salted_hash of this Data2.

          # noqa: E501

        :param salted_hash: The salted_hash of this Data2.  # noqa: E501
        :type: str
        """

        self._salted_hash = salted_hash

    @property
    def successful(self):
        """Gets the successful of this Data2.  # noqa: E501

          # noqa: E501

        :return: The successful of this Data2.  # noqa: E501
        :rtype: bool
        """
        return self._successful

    @successful.setter
    def successful(self, successful):
        """Sets the successful of this Data2.

          # noqa: E501

        :param successful: The successful of this Data2.  # noqa: E501
        :type: bool
        """

        self._successful = successful

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Data2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Data2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
